name: talknep

description: "A new Flutter project." 

publish_to: 'none'  

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter


#--------------state Management----------------#
  get: ^4.7.2
  provider: ^6.1.5


#--------------Network and connectivity----------------#
  http: ^1.4.0
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.4


#--------------Preferences----------------#
  logger: ^2.5.0
  shared_preferences: ^2.5.3


#--------------UI &  UX----------------#
  lottie: ^3.3.1
  shimmer: ^3.0.0 
  google_fonts: ^6.2.1 
  cupertino_icons: ^1.0.8
  flutter_spinkit: ^5.2.1
  flutter_slidable: ^4.0.1

#--------------Media ----------------#
  pod_player: ^0.2.2 
  flutter_svg: ^2.2.0 
  cached_network_image: ^3.4.1 

#--------------Firebase----------------#
  firebase_auth: ^5.7.0
  firebase_core: ^3.14.0
  google_sign_in: ^6.2.1 
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^19.4.0

#---------------Services----------------#
  geocoding: ^4.0.0
  image_picker: ^1.0.4 
  agora_rtc_engine: ^6.5.2
  google_maps_flutter: ^2.12.3
  pusher_channels_flutter: ^2.5.0 


#--------------Utility----------------# 
  share_plus: ^11.0.0 
  url_launcher: ^6.3.2 
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  flutter_advanced_avatar: ^1.5.2 
  flutter_launcher_icons: ^0.14.4
  

  flutter_localizations:
    sdk: flutter    
  uuid: ^4.5.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
   
  build_runner: ^2.6.0 
  flutter_gen_runner: ^5.11.0
 

flutter_gen:
  output: lib/gen/
  
  integrations:
    lottie: true
    flutter_svg: true

  assets:
    enabled: true
    outputs:
      class_name: Assets
      package_parameter_enabled: false


flutter:
  uses-material-design: true
  generate: true

  assets:
     - asset/icon/
     - asset/lottie/
     - asset/image/svg/
     - asset/image/png/
     
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700 


